### ISSUE TITLE
BUG: Layout Shift on Windows OS on Modal Open/Close

### ISSUE THREAD

**Issue by Yura33-dev** [naumch1k/one-fall#19]
### Description
Project have modal windows (eg. for Merch or Gallery). When modal window has been opened we`re facing with so-called 'layout shift' problem. It happens due to scroll-bar disappears and all centered content just shifts a bit to right side.

### Environment
**Desktop:**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: Chrome: 126.0.6478.127. Firefox: 127.0.2

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/ from desktop
2. Quickly try click on photo (Merch item or Gallery item) and close it.
3. See layout shift 

### Actual result:
You can see layout shift.
Also, after first click on merch item or gallery item, you can see horizontal scroll-bar at the bottom of window.

### Expected result:
Markup stay motionless. There is no horizontal scroll-bar.

### Attachments:
Layout shift:

https://github.com/user-attachments/assets/91bda4cf-374f-4b0c-8068-241df5329225

Scrolling page while modal window is open

https://github.com/user-attachments/assets/d80cf93c-94ed-46de-8a97-401e2a053389

### Additional context
Also, project have another issue which related to horizontal scroll-bar. When modal window opens, horizontal scroll-bar appears. 
Moreover, project requires to solve problem in iOS, when user can scroll page while mobile menu layout is open.
Perhaps, these issues are related and can be resolved by one solution. 

I would like to suggest solution in form of implement custom hook as complex solution to manage behaviour of scroll while modal windows are open. This hook should be deversity in oder to cover any differences in scroll behaviour implementation and guarantee positive user experience at high level.

[Article](https://blog.logrocket.com/create-advanced-scroll-lock-react-hook/) which can be usefull for this issue.

**Comment by naumch1k** [comment]
@Yura33-dev Thanks for dropping in with the issue and supporting it with screen recordings - that is super helpful to see what the alleged problem is.

I have a few questions to get a bit more details on iOS scroll behavior:

- What exact part of the screen are you applying the scrolling gesture to? Does the main page scroll when you are only touching the overlay menu, or is it just the part below that is not hidden?

- What particular iOS device are you using? I am interested in device screen width and height to see if that may be caused by us setting page min width to `414px` so that overlay menu height stops stretching to all available height.

The overlay menu is supposed to stretch to the full device height and not leave any of the page content visible while open. I wonder if this is part of the problem 🤔

```css
/* src/components/OverlayMenu/OverlayMenu.module.css */

.root {
  ...
  height: 100vh;
  ...
}
```

**Comment by Yura33-dev** [comment]
@naumch1k 👋

Yes, main page scrolls when I touching the overlay menu.

I have tested mobile menu on Iphone XS (375px × 812px viewport) and Iphone 13 (390px × 844px viewport).

Also, I have tested it again and discovered that sometimes horizontal scroll appears at mobile phone. You need to reduce zoom manually (by fingers 👆) and horizontal scroll will disappear.

One more video for understanding:


https://github.com/user-attachments/assets/6adebd5d-3bee-4451-bfbf-6e8184f8a388

**Comment by naumch1k** [comment]
@Yura33-dev Thank you for an additional information! 

I believe some of those issues, such as horizontal scroll on mobile, need to zoom out are caused by us restricting page min width.

I removed `needs triage` label and my name from assignees, so you can now proceed with implementing scroll lock hook ;)

**Comment by Yura33-dev** [comment]
.take
