### ISSUE TITLE
BUG: Hover Style is Applied to the 'PRESS' Menu Link after Closing the Modal Window by Tapping on the 'Close' Button

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#35]
### Description
This issue only occurs when closing a modal window by tapping on the 'Close' button in landscape mode. If the position of the tap is dirrectly over the 'PRESS' menu item, hover styles for the 'PRESS' menu link are applied.

### Environment
**Tablet**
Device: iPad (9th generation)
OS: iPadOS 17.6
Browser: Safari
Version: 17.6

### Preconditions:
1. Tablet is in landscape mode.

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/
2. Tap on the **MERCH** menu item.
3. Tap on any merch image for viewing it in full size.
4. Close the opened modal window by tapping on the close button.
5. Pay attantion to the 'PRESS' menu item.

### Actual result:
Hover style is applied to the 'PRESS' menu link after closing the modal window with full size merch image by tapping on the 'Close' button in landscape mode.

### Expected result:
Styles of the 'PRESS' menu link remain unchanged after closing the modal window with full size merch image by tapping on the 'Close' button in landscape mode.

### Attachments:
![merch_menu](https://github.com/user-attachments/assets/8d30fc97-1dd7-4ad7-b044-3e801433c032)

https://github.com/user-attachments/assets/e62d1e27-e34b-40b3-9599-6a1d3196676c

### Additional context
The same issue occurs after closing modal windows with full size gallery images. 
If the user is in the merch or gallery section and all main navigation menu items are fully displayed, after closing modal windows with full size images by tapping on the 'Close' button, the color of the 'PRESS' menu item is changed to another. Maybe this behavior of the 'PRESS' menu item is related to the main topic of this bug report.
![press_changed_color](https://github.com/user-attachments/assets/309c9154-8234-4198-a908-4f62ff1c3a6a)

https://github.com/user-attachments/assets/cde9f526-a30a-49fd-9241-379d253e450f

**Comment by naumch1k** [comment]
@yuliia-harshyna Hey! I have a few questions to better understand the issue:
- Were the videos provided recorded while using an iPad?
- Do you close the modal window by tapping the close button?
- Does the issue still occur if you close the modal by tapping on the backdrop?

**Comment by ghost** [comment]
> @yuliia-harshyna Hey! I have a few questions to better understand the issue:
> 
> * Were the videos provided recorded while using an iPad?
> * Do you close the modal window by tapping the close button?
> * Does the issue still occur if you close the modal by tapping on the backdrop?

Hello!
- Yes, I used an iPad.
- Yes, I closed the modal window by tapping the close button.
- If close the modal window by tapping on the backdrop the issue does not occur.

Thanks for your questions. I've edited steps to reproduce.

**Comment by naumch1k** [comment]
@yuliia-harshyna 👋 After examining this issue, I want to clarify what's actually happening.

The description of the problem, where the MERCH and PRESS nav links are both marked as the current location, isn't entirely accurate. The behavior is actually related to how **hover effects** are handled on touch devices like the iPad. 

When the modal is closed by tapping the close button, if the tap or cursor is positioned directly over the PRESS menu item, the hover styles (I temporarily added a yellow outline to demonstrate this in the screen recording) are applied to PRESS. This makes it appear as if PRESS looks the same as the current user position, but it's just a hover effect being triggered due to the position of the tap when the modal closes.

There are couple paragraphs on [doka.guide](https://doka.guide/css/hover/#na-praktike) that provide good explanation for specified behavior (you might need a VPN to open this page). 

> А что если на сайт зайти с планшета, к которому подключена bluetooth-мышь? Однозначно, ховер должен работать! А если дополнительных устройств ввода нет, то, конечно, стили по наведению должны быть сброшены, чтобы избежать визуального залипания при нажатии на соответствующие элементы.

> Пользователь может зайти на ваш сайт не только с десктопа, где есть мышка и её можно на что-то навести, но и с планшета или телефона, где мышкой выступает палец, а его нельзя на что-то навести, им можно только тапнуть.
Хорошая практика — сбрасывать :hover стили для тач-устройств. Иначе при нажатии на какой-то элемент ховер-стили будут залипать — телефон не знает, когда вы отводите палец в сторону.

Additionally, please note that we haven't yet implemented the highlight for the current user position when all navigation items are fully visible, as this is addressed in [another issue](https://github.com/naumch1k/one-fall/issues/28#issuecomment-2275774462).

If we close the modal by tapping on the backdrop or by tapping a part of the close button that isn't directly over the PRESS link, this hover effect doesn't occur, and only the MERCH item remains highlighted as expected.

I hope my explanation is clear; please let me know if you have any questions 👐 Could you please update the issue description to reflect an actual problem?

https://github.com/user-attachments/assets/868b890b-ec13-4c62-abdd-ec6dd7e427ed

**Comment by naumch1k** [comment]
.take

**Comment by ghost** [comment]
> @yuliia-harshyna 👋 After examining this issue, I want to clarify what's actually happening.
> 
> The description of the problem, where the MERCH and PRESS nav links are both marked as the current location, isn't entirely accurate. The behavior is actually related to how **hover effects** are handled on touch devices like the iPad.
> 
> When the modal is closed by tapping the close button, if the tap or cursor is positioned directly over the PRESS menu item, the hover styles (I temporarily added a yellow outline to demonstrate this in the screen recording) are applied to PRESS. This makes it appear as if PRESS looks the same as the current user position, but it's just a hover effect being triggered due to the position of the tap when the modal closes.
> 
> There are couple paragraphs on [doka.guide](https://doka.guide/css/hover/#na-praktike) that provide good explanation for specified behavior (you might need a VPN to open this page).
> 
> > А что если на сайт зайти с планшета, к которому подключена bluetooth-мышь? Однозначно, ховер должен работать! А если дополнительных устройств ввода нет, то, конечно, стили по наведению должны быть сброшены, чтобы избежать визуального залипания при нажатии на соответствующие элементы.
> 
> > Пользователь может зайти на ваш сайт не только с десктопа, где есть мышка и её можно на что-то навести, но и с планшета или телефона, где мышкой выступает палец, а его нельзя на что-то навести, им можно только тапнуть.
> > Хорошая практика — сбрасывать :hover стили для тач-устройств. Иначе при нажатии на какой-то элемент ховер-стили будут залипать — телефон не знает, когда вы отводите палец в сторону.
> 
> Additionally, please note that we haven't yet implemented the highlight for the current user position when all navigation items are fully visible, as this is addressed in [another issue](https://github.com/naumch1k/one-fall/issues/28#issuecomment-2275774462).
> 
> If we close the modal by tapping on the backdrop or by tapping a part of the close button that isn't directly over the PRESS link, this hover effect doesn't occur, and only the MERCH item remains highlighted as expected.
> 
> I hope my explanation is clear; please let me know if you have any questions 👐 Could you please update the issue description to reflect an actual problem?
> 
>  ipad-hovers.mp4

Your explanation is completely clear. Thank you. I'll make all changes.
